#!/bin/bash

rversion=2.15.1

echo "-----------> step 1: executing build-r"
tar czf build2.tgz build-r

# echo "-----------> step 2: vulcan build"
# vulcan build --source=./build.tgz \
#              --prefix=/app/vendor \
#              --command="./build-r $rversion" \
#              --verbose

echo "-----------> step 2: anvil build"
heroku build build2.tgz

echo "-----------> step 3: remove files after build"
rm build2.tgz
